config/routes.rb
Rails.application.routes.draw do
  get 'comments/comment_history'

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable do
   resources :answers, concerns: :commentable
  end

  devise_for :users

  root 'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :answered_users, :source => :user, :through => :answers
  has_many :comments, as: :commentable

  validates :quesbox, :presence => true



end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :require_permission, only: [:edit, :destroy]

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = current_user.questions.new
  end

  def create
    @question = current_user.questions.new(post_params)
    #@question.user = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: questions_path}
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    if @question.update(post_params)
      redirect_to questions_path, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
#end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:question).permit(:quesbox)
    end

    def require_permission
    if current_user != @question.user
      respond_to do |format|
      format.html { redirect_to questions_path,notice: 'You are not allowed to access this questions' }
    end
      end
    end


end

app/helpers/questions_helper.rb
module QuestionsHelper
  def ques_error_messages
    return '' if @question.errors.empty?
    flash.now[:error] = @question.errors.full_messages.map { |msg| "#{msg}." }[0]
  end
end

app/views/questions/_form.html.haml
.col-lg-3
.col-lg-6
  = form_for(@question) do |f|
    - ques_error_messages
    .field
      = f.label :Question
      %br/
      = f.text_area :quesbox,class: "form-control",:rows => 7
    %br/
    .actions
      = f.submit "Create Question", :class => "btn btn-primary"
      = link_to 'Back', questions_path

.col-lg-3

app/views/questions/edit.html.haml
%h1 Editing Post
= render 'form'

app/views/questions/index.html.haml
- @questions.each do |question|
  .question_list
    =Question.new.meth
    = link_to question.quesbox, question
    - if current_user == question.user
      = link_to 'Edit', edit_question_path(question), class: "btn btn-primary btn-xs"
      = link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary btn-xs"
%br/
= link_to 'Create Question', new_question_path, class: "btn btn-primary btn-xs"

app/views/questions/new.html.haml
= render 'form'

app/views/questions/show.html.haml
%button{:onclick => "myFunction()"} Click
%span.question= @question.quesbox
%span.fullname= @question.user.fullname
%hr
= render partial: "comments/index", locals: {comments: @comments, question: @question}
%br/
.comment= link_to 'Add Comment', new_question_comment_path(@question)
/= render partial: "answers/index", locals: {comments: @comments, answers: @answers, question: @question}
= render "answers/index"


%br/