config/routes.rb
Rails.application.routes.draw do
  get 'comments/comment_history'

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable do
   resources :answers, concerns: :commentable
  end

  devise_for :users

  root 'questions#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates :comment, presence: true

 def check_history?
   self.history_id.blank?
 end

 def self.show_history(num)
   where("history_id IS NULL AND id =? OR history_id =? AND id != ?", num, num, num).order("id DESC").first
 end

 def self.list_comment_history(num,not_num)
   where("history_id IS NULL AND id =? XOR history_id =? AND id != ? AND id != ?",num,num,num, not_num).order("id DESC")
 end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :find_question, only: [:show, :create, :edit, :update, :new, :destroy]

  def new
    commentable= find_commentable
    @commentable= commentable.comments.new
  end

  def index
    @comments = Comment.all
  end

  def create
    commentable= find_commentable
    @commentable= commentable.comments.new(post_params)
    @commentable.user = current_user
    #@question.user = current_user

    respond_to do |format|
      if @commentable.save
        if(@commentable.commentable_type == "Question")
          #redirect_to question_path, notice: "The interaction has been successfully created"
          format.html { redirect_to @question, notice: 'Comment was successfully created.' }

        else
          #redirect_to question_answer_path, notice: "The interaction has been successfully created"
          format.html { redirect_to @question, notice: 'Comment Answer was successfully created.' }
        end
      else
        format.html { render :new }
      end
    end
  end

  def update
    #@commentable.update(post_params)

    commentable = find_commentable
    if @commentable.check_history?
     params = post_params.merge(history_id: @commentable.id)
     @commentable = commentable.comments.new(params)
     @commentable.user = current_user
     @commentable.save
   else
     params = post_params.merge(history_id: @commentable.history_id)
     @commentable = commentable.comments.new(params)
     @commentable.user = current_user
     @commentable.save
    end

    if (@commentable.commentable_type == "Question")
      redirect_to @question, notice: 'Comment was successfully updated.'
    else
      redirect_to @question, notice: 'Comment Answer was successfully updated.'
    end
  end

  def edit
  end

  def destroy
    @commentable.destroy
    if (@commentable.commentable_type == "Question")
      redirect_to @question, notice: 'Comment was successfully destroyed.'
    else
      redirect_to @question, notice: 'Comment Answer was successfully destroyed.'
    end
  end

  def comment_history
   @comment_history = Comment.list_comment_history(params[:history_id], params[:dont_show])
   # Comment.where("history_id IS NULL AND id =? XOR history_id =? AND id != ?", 143,143, 143).order("id DESC").first
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.

  def find_commentable
    if params[:question_id] && params[:answer_id]
      klass = "answers"
      id = params[:answer_id]
    else
      klass = "questions"
      id = params[:question_id]
    end
    return "#{klass}".singularize.classify.constantize.find(id)
  end

  def set_post
    @commentable = Comment.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:comment).permit(:comment)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def com_error_messages
    return '' if @commentable.errors.empty?
    flash.now[:error] = @commentable.errors.full_messages.map { |msg| "#{msg}." }[0]
  end
end

app/views/comments/_form.html.haml
.col-lg-3
.col-lg-6
  = form_for([@question, @commentable]) do |f|
    -com_error_messages
    .field
      = f.label :Comments
      %br/
      = f.text_area :comment,class: "form-control",:rows => 7
        - if params[:answer_id].present?
        =hidden_field_tag :answer_id, params[:answer_id]
    %br/
    .actions
      = f.submit "Create Comment", :class => "btn btn-primary"
.col-lg-3

app/views/comments/_index.html.haml
.comment
  - question.comments.where("history_id IS NULL").each do |comment|
    .question_comment
      - question_comment = Comment.show_history(comment.id)
      %span= question_comment.comment
      %span.fullname= "- #{question_comment.user.fullname}"
      - if current_user == question_comment.user
        = link_to 'Edit', edit_question_comment_path(id: comment.id, question_id:question)
        - unless question_comment.check_history?
          = link_to 'Edited', comments_comment_history_path(history_id: question_comment.history_id, dont_show: question_comment.id)
        = link_to 'Destroy', question_comment_path(id: comment.id, question_id:question), method: :delete, data: { confirm: 'Are you sure?' }

app/views/comments/comment_history.html.haml
.answer-comment
  - @comment_history.each do |comment|
    %span= comment.comment
    %span.fullname= "- #{comment.user.fullname}"
    %br/
    %br/

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.haml
%h1 Editing Post
= render 'form'

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>