config/routes.rb
Rails.application.routes.draw do
  get 'comments/comment_history'

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable do
   resources :answers, concerns: :commentable
  end

  devise_for :users

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable, dependent: :destroy
  validates :answer, :presence => true
  validates :user_id, :uniqueness => { :scope => :question_id, :message => "you are not allowed to create the answer"}


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :find_question, only: [:show, :create, :new, :edit, :update, :destroy]
  before_filter :require_permission, only: [:new, :create]

  def new
    @answer= @question.answers.new
  end

  def create
    @answer= @question.answers.new(post_params)
    @answer.user = current_user
    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @question}
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @answer.update(post_params)
      redirect_to @question, notice: 'Answer was successfully updated.'
    else
      render :edit
    end
  end

  def edit

  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @question, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index
    @answers = Answer.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_post
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:answer).permit(:answer)
  end

  def require_permission
    unless current_user.answers.where(question_id: @question).first.blank?
      respond_to do |format|
        format.html { redirect_to @question,notice: 'You are not allowed to create the answer' }
      end
    end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
  def ans_error_messages
    return '' if @answer.errors.empty?
    flash.now[:error] = @answer.errors.full_messages.map { |msg| "#{msg}." }[0]
  end
end

app/views/answers/_form.html.haml
.col-lg-3
.col-lg-6
  = form_for([@question, @answer]) do |f|
    -ans_error_messages
    .field
      = f.label :Answers
      %br/
      = f.text_area :answer,class: "form-control",:rows => 7
    %br/
    .actions
      = f.submit "Create Answer", class: "btn btn-primary"
.col-lg-3

app/views/answers/_index.html.haml
%br/
%span= @question.answers.count
%span= @question.user.anscount
- if current_user.answers.where(question_id: @question).first.blank?
  %span.ans_comment= link_to 'Add Answer', new_question_answer_path(@question)
%hr
- @question.answers.each do|answer|
  .question_answer
    %span.answer= answer.answer
    %span.fullname= "-#{answer.user.fullname}"
    - if current_user == answer.user
      = link_to 'Edit', edit_question_answer_path(id: answer.id, question_id:@question)
      = link_to 'Destroy',question_answer_path(id: answer.id, question_id:@question), method: :delete, data: { confirm: 'Are you sure?' }
  %hr

  - answer.comments.where("history_id IS NULL").each do|comment|
    .answer_comment
      - answer_comment = Comment.show_history(comment.id)
      %span= answer_comment.comment
      %span.fullname="- #{comment.user.fullname}"
      - if current_user == comment.user
        = link_to 'Edit', edit_question_answer_comment_path(id: comment.id, answer_id: answer.id,question_id:@question)
        - unless answer_comment.check_history?
          = link_to 'Edited', comments_comment_history_path(history_id: answer_comment.history_id, dont_show: answer_comment.id)
        = link_to 'Destroy',question_answer_comment_path(id: comment.id,answer_id: answer.id,question_id:@question), method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  .comment= link_to 'Add Comment', new_question_answer_comment_path(@question, answer)
  %hr

app/views/answers/create.html.haml
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/destroy.html.haml
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

app/views/answers/edit.html.haml
%h1 Editing Post
= render 'form'

app/views/answers/index.html.haml
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/answers/new.html.haml
= render 'form'

app/views/answers/show.html.haml
/= @answer.answer
= link_to 'Add Comment', new_question_answer_comment_path(@question,@answer)
%br/
%h4 Answer Comments
%table
  %tbody
    - @answer.comments.each do|c|
      %tr
      %td= c.comment
      %td= c.user.fullname
      - if current_user == c.user
        %td= link_to 'Edit', edit_question_answer_comment_path(id: c.id, answer_id:@answer,question_id:@question)
        %td= link_to 'Destroy',question_answer_comment_path(id: c.id,answer_id:@answer,question_id:@question), method: :delete, data: { confirm: 'Are you sure?' }

app/views/answers/update.html.haml
<h1>Answers#update</h1>
<p>Find me in app/views/answers/update.html.erb</p>